sudo: required
dist: trusty

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - chmod +x ./volume/init.sh
  - ./volume/init.sh dev
  - docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
  - docker logs app
  - docker exec --privileged -it app ls
  - docker exec --privileged -it app ls ./node_modules/.bin/
  # - docker exec --privileged -it app ./node_modules/.bin/mocha --help
  - docker exec --privileged -it app npm test

script:
  - docker exec --privileged -it app npm test

after_script:
  - docker logs app
  - docker-compose down
  - docker volume rm $(docker volume ls -qf dangling=true)