version: '2'
services: 
  app:
    container_name: app
    build: .
    restart: always
    ports: 
      - "4000:4000"
    environment:
      - NODE_PATH=./app
  db:
    container_name: db
    build: ./db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
      - ./db/config/mongod.conf:/etc/mongod.conf
volumes:
  data:
    external: true